try use nginx

diff --git a/.github/workflows/main_cicd.yaml b/.github/workflows/main_cicd.yaml
--- a/.github/workflows/main_cicd.yaml
+++ b/.github/workflows/main_cicd.yaml
@@ -36,8 +36,7 @@ jobs:
             cd ~/projects/nsau_timetable/
             git checkout master
             git pull
-            export DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING}}
             if [ -f deploy.sh ]
             then bash deploy.sh || exit 1
-            else echo "deploy script not found"
+            else echo "deploy script not found" && exit 1
             fi
